/**
 * Seed the Endläufe 2026 data set from `data/endlauf26/`.
 *
 *  hmj       `hmj.json` (generated by `scripts/endlauf26/parse-pdfs.py` from
 *            the official standings PDF). Every driver of the list is
 *            imported; the qualified ones (plus admins' Nachnominierungen)
 *            form the field, the rest is the pool of replacement candidates.
 *
 *  adac_hth  `adac-hth_endlauf2026.csv` — the FINAL start list and single
 *            source of truth for the field (class, starting position of
 *            Endlauf 1, regional position → points, club, region, Nachrücker).
 *            Drivers of earlier imports that are not on the list are deleted
 *            (unless an official result exists for them), as are clubs that
 *            end up without drivers. `adac-hth.json` (regional standings
 *            PDFs) is only used to enrich matching drivers with Ausweis-Nr.,
 *            season totals and per-race results.
 *
 * Idempotent: teams/drivers/season results are upserted on their natural
 * keys; events are upserted by (championship, slug). hmj entries are only
 * inserted when missing (bottom-up starting order); ADAC entries take the
 * starting position of the CSV for every class that has no live times yet.
 * The admin flag `withdrawn` is never touched; `nominated` follows the CSV
 * for adac_hth and is left alone for hmj. Official results / photos
 * (`endlauf26_results`, `endlauf26_result_images`) are never touched. The
 * source documents are stored when the slot is still empty.
 *
 * Run:  cd webapp && npm run db:seed-endlauf26
 *       (or `make seed-endlauf26` from the project root)
 */
import "dotenv/config";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { and, eq, inArray, isNotNull, notInArray, or, sql } from "drizzle-orm";

import * as schema from "../src/db/schema";
import {
  ADAC_FIELD_CSV,
  parseAdacFieldCsv,
  type AdacFieldEntry,
} from "../src/lib/endlauf26/adac-field";
import { ENDLAUF26_DOCUMENT_SLOTS } from "../src/lib/endlauf26/documents";
import { nameKey, namesMatch, nameTokens } from "../src/lib/endlauf26/names";
import {
  computeEndlauf26Championship,
  type Endlauf26Championship,
  type EndlaufDriverInput,
} from "../src/lib/endlauf26/ranking";

const __filename = fileURLToPath(import.meta.url);

function resolveDataDir(): string {
  const scriptDir = dirname(__filename);
  const candidates = [
    join(dirname(dirname(scriptDir)), "data", "endlauf26"), // repo root
    join(dirname(scriptDir), "data", "endlauf26"), // /app/data in container
  ];
  for (const dir of candidates) {
    if (existsSync(join(dir, "hmj.json"))) return dir;
  }
  throw new Error(`data/endlauf26 not found (tried: ${candidates.join(", ")})`);
}

const DATA_DIR = resolveDataDir();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("ENV ERROR - DATABASE_URL is missing");
const db = drizzle(databaseUrl, { schema });

/* ───────────────────────────── JSON shapes ───────────────────────────── */

interface JsonResult {
  race: number;
  position: number;
  points: number;
  struck: boolean;
}

interface JsonDriver {
  position: number;
  qualified: boolean;
  lastName: string;
  firstName: string;
  club: string;
  racesStarted: number;
  total: number;
  results: JsonResult[];
  verband?: string | null;
  adacId?: string | null;
}

interface JsonClass {
  number: number;
  drivers: JsonDriver[];
}

interface HmjJson {
  championship: "hmj";
  stand: string;
  classes: JsonClass[];
}

interface AdacJson {
  championship: "adac-hth";
  regions: { region: string; stand: string; classes: JsonClass[] }[];
}

/* ───────────────────────────── events ───────────────────────────── */

const EVENTS: Record<
  Endlauf26Championship,
  { number: number; slug: string; name: string; factor: string }[]
> = {
  hmj: [
    { number: 1, slug: "langgoens-1", name: "Langgöns 1", factor: "1.25" },
    { number: 2, slug: "langgoens-2", name: "Langgöns 2", factor: "1.25" },
  ],
  adac_hth: [
    { number: 1, slug: "crumbach", name: "Crumbach", factor: "1.00" },
    { number: 2, slug: "reinheim", name: "Reinheim", factor: "1.00" },
    { number: 3, slug: "malsfeld", name: "Malsfeld", factor: "1.10" },
  ],
};

/* ───────────────────────────── helpers ───────────────────────────── */

async function upsertTeam(
  championship: Endlauf26Championship,
  name: string,
): Promise<number> {
  await db
    .insert(schema.endlauf26Teams)
    .values({ championship, name })
    .onConflictDoNothing();
  const [row] = await db
    .select({ id: schema.endlauf26Teams.id })
    .from(schema.endlauf26Teams)
    .where(
      and(
        eq(schema.endlauf26Teams.championship, championship),
        eq(schema.endlauf26Teams.name, name),
      ),
    )
    .limit(1);
  return row.id;
}

interface DriverValues {
  championship: Endlauf26Championship;
  firstName: string;
  lastName: string;
  club: string;
  ageClass: number;
  verband: string | null;
  region: string | null;
  adacId: string | null;
  seasonPosition: number;
  seasonPoints: number | null;
  seasonRaces: number;
  qualified: boolean;
  /**
   * Set `nominated` from the source (adac_hth: "Nachrücker" column of the
   * start list). Undefined = leave the admin decision alone (hmj).
   */
  nominated?: boolean;
  results: JsonResult[];
}

async function upsertDriver(
  v: DriverValues,
  teamIdByName: Map<string, number>,
): Promise<number> {
  let teamId = teamIdByName.get(v.club);
  if (!teamId) {
    teamId = await upsertTeam(v.championship, v.club);
    teamIdByName.set(v.club, teamId);
  }
  const values = {
    championship: v.championship,
    firstName: v.firstName,
    lastName: v.lastName,
    teamId,
    ageClass: v.ageClass,
    verband: v.verband,
    region: v.region,
    adacId: v.adacId,
    seasonPosition: v.seasonPosition,
    seasonPoints: v.seasonPoints === null ? null : String(v.seasonPoints),
    seasonRaces: v.seasonRaces,
    qualified: v.qualified,
    ...(v.nominated === undefined ? {} : { nominated: v.nominated }),
  };
  const [row] = await db
    .insert(schema.endlauf26Drivers)
    .values(values)
    .onConflictDoUpdate({
      target: [
        schema.endlauf26Drivers.championship,
        schema.endlauf26Drivers.firstName,
        schema.endlauf26Drivers.lastName,
        schema.endlauf26Drivers.teamId,
      ],
      // `withdrawn` is an admin decision — deliberately not reset.
      set: {
        ageClass: values.ageClass,
        verband: values.verband,
        region: values.region,
        // Never wipe an Ausweis-Nr. that was filled in from a result list.
        adacId: values.adacId === null ? sql`${schema.endlauf26Drivers.adacId}` : values.adacId,
        seasonPosition: values.seasonPosition,
        seasonPoints: values.seasonPoints,
        seasonRaces: values.seasonRaces,
        qualified: values.qualified,
        ...(v.nominated === undefined ? {} : { nominated: v.nominated }),
      },
    })
    .returning({ id: schema.endlauf26Drivers.id });

  for (const r of v.results) {
    await db
      .insert(schema.endlauf26SeasonResults)
      .values({
        driverId: row.id,
        raceNumber: r.race,
        finishPosition: r.position,
        points: r.points,
        struckInSource: r.struck,
      })
      .onConflictDoUpdate({
        target: [
          schema.endlauf26SeasonResults.driverId,
          schema.endlauf26SeasonResults.raceNumber,
        ],
        set: {
          finishPosition: r.position,
          points: r.points,
          struckInSource: r.struck,
        },
      });
  }
  return row.id;
}

function fromJsonDriver(
  championship: Endlauf26Championship,
  ageClass: number,
  d: JsonDriver,
  region: string | null,
): DriverValues {
  return {
    championship,
    firstName: d.firstName,
    lastName: d.lastName,
    club: d.club,
    ageClass,
    verband: championship === "hmj" ? (d.verband ?? null) : null,
    region,
    adacId: d.adacId ?? null,
    seasonPosition: d.position,
    seasonPoints: d.total,
    seasonRaces: d.racesStarted,
    qualified: d.qualified,
    results: d.results,
  };
}

/* ───────────────────────── adac_hth: the final field ───────────────────────── */

interface AdacEnrichment {
  ageClass: number;
  driver: JsonDriver;
}

/**
 * Find the driver of the regional standings (adac-hth.json) behind a CSV
 * line: same class, same person by tolerant name match (spelling differs
 * between the lists — "Hoffman"/"Hoffmann"). Ambiguous → none.
 */
function findEnrichment(e: AdacFieldEntry, pool: readonly AdacEnrichment[]): AdacEnrichment | null {
  const tokens = nameTokens(e.rawName);
  const exact = pool.filter(
    (p) => p.ageClass === e.ageClass && nameKey(p.driver.lastName, p.driver.firstName) === tokens.join(" "),
  );
  if (exact.length === 1) return exact[0];
  if (exact.length > 1) return null;
  const fuzzy = pool.filter(
    (p) => p.ageClass === e.ageClass && namesMatch(tokens, nameTokens(p.driver.lastName, p.driver.firstName)),
  );
  return fuzzy.length === 1 ? fuzzy[0] : null;
}

interface AdacSeedResult {
  /** driverId per CSV line, in CSV order. */
  drivers: { entry: AdacFieldEntry; driverId: number }[];
  enriched: number;
  clubs: number;
}

/**
 * Upsert the ADAC field from the CSV. Names keep the split of the standings
 * list when the driver is found there (so existing rows — and with them
 * entries, results and predictions — keep their identity); otherwise the
 * first token is the last name.
 */
async function seedAdacField(
  field: readonly AdacFieldEntry[],
  adac: AdacJson,
): Promise<AdacSeedResult> {
  const pool: AdacEnrichment[] = [];
  for (const region of adac.regions) {
    for (const c of region.classes) {
      for (const d of c.drivers) pool.push({ ageClass: c.number, driver: d });
    }
  }

  const teamIdByName = new Map<string, number>();
  const drivers: AdacSeedResult["drivers"] = [];
  let enriched = 0;
  for (const e of field) {
    const match = findEnrichment(e, pool);
    if (match) enriched += 1;
    const id = await upsertDriver(
      {
        championship: "adac_hth",
        firstName: match ? match.driver.firstName : e.firstName,
        lastName: match ? match.driver.lastName : e.lastName,
        club: e.club,
        ageClass: e.ageClass,
        verband: null,
        region: e.region,
        adacId: match?.driver.adacId ?? null,
        seasonPosition: e.seasonPosition,
        seasonPoints: match ? match.driver.total : null,
        seasonRaces: match ? match.driver.racesStarted : 0,
        // Nachrücker are part of the field like everybody else, but flagged.
        qualified: !e.nachruecker,
        nominated: e.nachruecker,
        results: match ? match.driver.results : [],
      },
      teamIdByName,
    );
    drivers.push({ entry: e, driverId: id });
  }
  return { drivers, enriched, clubs: teamIdByName.size };
}

/**
 * Remove ADAC drivers of earlier imports that are not on the start list —
 * the CSV is the whole field, there is no replacement pool any more. A
 * driver with an official result is kept (and reported) instead. Clubs
 * without drivers go too.
 */
async function pruneAdacField(keepIds: readonly number[]) {
  const stale = await db
    .select({
      id: schema.endlauf26Drivers.id,
      firstName: schema.endlauf26Drivers.firstName,
      lastName: schema.endlauf26Drivers.lastName,
      ageClass: schema.endlauf26Drivers.ageClass,
    })
    .from(schema.endlauf26Drivers)
    .where(
      and(
        eq(schema.endlauf26Drivers.championship, "adac_hth"),
        keepIds.length ? notInArray(schema.endlauf26Drivers.id, [...keepIds]) : undefined,
      ),
    );
  if (stale.length === 0) return { deleted: 0, kept: [] as string[], teams: 0 };

  const withResults = new Set(
    (
      await db
        .selectDistinct({ driverId: schema.endlauf26Results.driverId })
        .from(schema.endlauf26Results)
        .where(
          inArray(
            schema.endlauf26Results.driverId,
            stale.map((s) => s.id),
          ),
        )
    ).map((r) => r.driverId),
  );
  const kept: string[] = [];
  const toDelete: number[] = [];
  for (const s of stale) {
    if (withResults.has(s.id)) kept.push(`${s.lastName} ${s.firstName} (K${s.ageClass})`);
    else toDelete.push(s.id);
  }
  if (toDelete.length) {
    // Season results, entries, predictions cascade.
    await db.delete(schema.endlauf26Drivers).where(inArray(schema.endlauf26Drivers.id, toDelete));
  }

  const orphanTeams = await db
    .select({ id: schema.endlauf26Teams.id })
    .from(schema.endlauf26Teams)
    .where(
      and(
        eq(schema.endlauf26Teams.championship, "adac_hth"),
        sql`not exists (select 1 from ${schema.endlauf26Drivers} where ${schema.endlauf26Drivers.teamId} = ${schema.endlauf26Teams.id})`,
      ),
    );
  if (orphanTeams.length) {
    await db.delete(schema.endlauf26Teams).where(
      inArray(
        schema.endlauf26Teams.id,
        orphanTeams.map((t) => t.id),
      ),
    );
  }
  return { deleted: toDelete.length, kept, teams: orphanTeams.length };
}

/**
 * Entries of every ADAC Endlauf with the starting position of the CSV
 * (column 2 = Startplatz Endlauf 1). Applied to every event whose class has
 * no live times yet; a class already underway keeps its order.
 */
async function seedAdacEntries(drivers: AdacSeedResult["drivers"]) {
  const events = await db
    .select()
    .from(schema.endlauf26Events)
    .where(eq(schema.endlauf26Events.championship, "adac_hth"));
  const underway = new Set(
    (
      await db
        .selectDistinct({
          eventId: schema.endlauf26Entries.eventId,
          ageClass: schema.endlauf26Entries.ageClass,
        })
        .from(schema.endlauf26Entries)
        .innerJoin(schema.endlauf26Events, eq(schema.endlauf26Events.id, schema.endlauf26Entries.eventId))
        .where(
          and(
            eq(schema.endlauf26Events.championship, "adac_hth"),
            or(
              isNotNull(schema.endlauf26Entries.testTime),
              isNotNull(schema.endlauf26Entries.run1Time),
              isNotNull(schema.endlauf26Entries.run2Time),
            ),
          ),
        )
    ).map((r) => `${r.eventId}:${r.ageClass}`),
  );

  let inserted = 0;
  let reordered = 0;
  let skipped = 0;
  for (const ev of events) {
    for (const { entry, driverId } of drivers) {
      const locked = underway.has(`${ev.id}:${entry.ageClass}`);
      const res = await db
        .insert(schema.endlauf26Entries)
        .values({
          eventId: ev.id,
          driverId,
          ageClass: entry.ageClass,
          startingOrder: entry.startPosition,
        })
        .onConflictDoUpdate({
          target: [schema.endlauf26Entries.eventId, schema.endlauf26Entries.driverId],
          set: locked
            ? { ageClass: entry.ageClass }
            : { ageClass: entry.ageClass, startingOrder: entry.startPosition },
        })
        .returning({
          id: schema.endlauf26Entries.id,
          inserted: sql<boolean>`(xmax = 0)`,
        });
      if (res[0]?.inserted) inserted += 1;
      else if (locked) skipped += 1;
      else reordered += 1;
    }
  }
  console.log(
    `  adac_hth: ${inserted} new entries, ${reordered} starting positions set from the CSV, ${skipped} kept (class underway) across ${events.length} events`,
  );
}

async function seedEvents(championship: Endlauf26Championship) {
  for (const e of EVENTS[championship]) {
    await db
      .insert(schema.endlauf26Events)
      .values({ championship, ...e })
      .onConflictDoUpdate({
        target: [schema.endlauf26Events.championship, schema.endlauf26Events.slug],
        set: { number: e.number, name: e.name, factor: e.factor },
      });
  }
}

/**
 * hmj: create the entry list of every event — every driver of the Endlauf
 * field (qualified or nominated), starting order bottom-up (worst pre-Endlauf
 * standing starts first). Existing entries are left alone.
 */
async function seedEntries(championship: Endlauf26Championship) {
  const drivers = await db
    .select({
      id: schema.endlauf26Drivers.id,
      firstName: schema.endlauf26Drivers.firstName,
      lastName: schema.endlauf26Drivers.lastName,
      teamId: schema.endlauf26Drivers.teamId,
      ageClass: schema.endlauf26Drivers.ageClass,
      verband: schema.endlauf26Drivers.verband,
      region: schema.endlauf26Drivers.region,
      adacId: schema.endlauf26Drivers.adacId,
      yearOfBirth: schema.endlauf26Drivers.yearOfBirth,
      seasonPosition: schema.endlauf26Drivers.seasonPosition,
      seasonPoints: schema.endlauf26Drivers.seasonPoints,
      seasonRaces: schema.endlauf26Drivers.seasonRaces,
      withdrawn: schema.endlauf26Drivers.withdrawn,
      nominated: schema.endlauf26Drivers.nominated,
    })
    .from(schema.endlauf26Drivers)
    .where(
      and(
        eq(schema.endlauf26Drivers.championship, championship),
        or(
          eq(schema.endlauf26Drivers.qualified, true),
          eq(schema.endlauf26Drivers.nominated, true),
        ),
      ),
    );

  const seasonRows = await db
    .select()
    .from(schema.endlauf26SeasonResults)
    .innerJoin(
      schema.endlauf26Drivers,
      eq(schema.endlauf26Drivers.id, schema.endlauf26SeasonResults.driverId),
    )
    .where(eq(schema.endlauf26Drivers.championship, championship));
  const seasonByDriver = new Map<number, typeof seasonRows>();
  for (const r of seasonRows) {
    const arr = seasonByDriver.get(r.endlauf26_season_results.driverId) ?? [];
    arr.push(r);
    seasonByDriver.set(r.endlauf26_season_results.driverId, arr);
  }

  const inputs: EndlaufDriverInput[] = drivers.map((d) => ({
    driverId: d.id,
    firstName: d.firstName,
    lastName: d.lastName,
    teamId: d.teamId,
    teamName: "",
    ageClass: d.ageClass,
    verband: d.verband,
    region: d.region,
    adacId: d.adacId,
    yearOfBirth: d.yearOfBirth,
    seasonPosition: d.seasonPosition,
    seasonPoints: d.seasonPoints === null ? null : Number(d.seasonPoints),
    seasonRaces: d.seasonRaces,
    withdrawn: d.withdrawn,
    nominated: d.nominated,
    seasonResults: (seasonByDriver.get(d.id) ?? []).map((r) => ({
      raceNumber: r.endlauf26_season_results.raceNumber,
      finishPosition: r.endlauf26_season_results.finishPosition,
      points: r.endlauf26_season_results.points,
    })),
    endlaufResults: [],
  }));

  const events = await db
    .select()
    .from(schema.endlauf26Events)
    .where(eq(schema.endlauf26Events.championship, championship));

  const rows = computeEndlauf26Championship(
    championship,
    inputs,
    events.map((e) => ({
      eventId: e.id,
      number: e.number,
      slug: e.slug,
      name: e.name,
      factor: Number(e.factor),
    })),
  );

  // Bottom-up: last place in the class starts first.
  const startingOrder = new Map<number, number>();
  const byClass = new Map<number, typeof rows>();
  for (const r of rows) {
    byClass.set(r.ageClass, [...(byClass.get(r.ageClass) ?? []), r]);
  }
  for (const list of byClass.values()) {
    const bottomUp = [...list].reverse();
    bottomUp.forEach((r, idx) => startingOrder.set(r.driverId, idx + 1));
  }

  let inserted = 0;
  for (const ev of events) {
    for (const d of drivers) {
      const res = await db
        .insert(schema.endlauf26Entries)
        .values({
          eventId: ev.id,
          driverId: d.id,
          ageClass: d.ageClass,
          startingOrder: startingOrder.get(d.id) ?? null,
        })
        .onConflictDoNothing()
        .returning({ id: schema.endlauf26Entries.id });
      inserted += res.length;
    }
  }
  console.log(`  ${championship}: ${inserted} new entries across ${events.length} events`);
}

/**
 * Store the official source documents (standings PDFs, the ADAC start-list
 * CSV) so they can be opened from the app. Only fills empty slots — a file
 * an admin uploaded/replaced via the UI is never overwritten by the seed.
 */
async function seedDocuments() {
  for (const championship of Object.keys(ENDLAUF26_DOCUMENT_SLOTS) as Endlauf26Championship[]) {
    for (const slot of ENDLAUF26_DOCUMENT_SLOTS[championship]) {
      const file = join(DATA_DIR, slot.seedFile);
      if (!existsSync(file)) {
        console.log(`  ${championship}/${slot.key}: ${slot.seedFile} not found — skipped`);
        continue;
      }
      const data = readFileSync(file);
      const res = await db
        .insert(schema.endlauf26Documents)
        .values({
          championship,
          key: slot.key,
          filename: slot.seedFile.split("/").pop() ?? slot.seedFile,
          mime: slot.mime,
          size: data.byteLength,
          data,
        })
        .onConflictDoNothing()
        .returning({ id: schema.endlauf26Documents.id });
      console.log(
        `  ${championship}/${slot.key}: ${slot.seedFile} (${(data.byteLength / 1024).toFixed(0)} KB) ${res.length > 0 ? "stored" : "already present"}`,
      );
    }
  }
}

/* ───────────────────────────── main ───────────────────────────── */

async function seed() {
  const hmj = JSON.parse(
    readFileSync(join(DATA_DIR, "hmj.json"), "utf-8"),
  ) as HmjJson;
  const adac = JSON.parse(
    readFileSync(join(DATA_DIR, "adac-hth.json"), "utf-8"),
  ) as AdacJson;

  const field = parseAdacFieldCsv(readFileSync(join(DATA_DIR, ADAC_FIELD_CSV), "utf-8"));

  // hmj
  console.log(`Seeding hmj (Stand ${hmj.stand})…`);
  {
    const teamIdByName = new Map<string, number>();
    let qualified = 0;
    let reserve = 0;
    for (const c of hmj.classes) {
      for (const d of c.drivers) {
        await upsertDriver(fromJsonDriver("hmj", c.number, d, null), teamIdByName);
        if (d.qualified) qualified += 1;
        else reserve += 1;
      }
    }
    console.log(
      `  ${qualified} qualified drivers, ${reserve} replacement candidates, ${teamIdByName.size} clubs`,
    );
  }

  // adac-hth: the final start list is the field
  console.log(`Seeding adac-hth from ${ADAC_FIELD_CSV} (${field.length} starters)…`);
  const adacSeed = await seedAdacField(field, adac);
  {
    const nachruecker = field.filter((e) => e.nachruecker).length;
    const perClass = [1, 2, 3, 4, 5, 6]
      .map((c) => `K${c}: ${field.filter((e) => e.ageClass === c).length}`)
      .join(", ");
    console.log(
      `  ${field.length - nachruecker} qualified drivers + ${nachruecker} Nachrücker (${perClass}), ${adacSeed.clubs} clubs`,
    );
    console.log(
      `  ${adacSeed.enriched}/${field.length} drivers enriched from the regional standings (Ausweis-Nr., season results)`,
    );
    const renamedClubs = field.filter((e) => e.club !== e.rawClub);
    if (renamedClubs.length) {
      const pairs = [...new Set(renamedClubs.map((e) => `"${e.rawClub}" → "${e.club}"`))];
      console.log(`  club spellings normalised: ${pairs.join(", ")}`);
    }
    const pruned = await pruneAdacField(adacSeed.drivers.map((d) => d.driverId));
    console.log(
      `  ${pruned.deleted} drivers not on the start list removed, ${pruned.teams} clubs without drivers removed`,
    );
    if (pruned.kept.length) {
      console.log(
        `  WARNING: kept ${pruned.kept.length} drivers that are not on the start list but have official results: ${pruned.kept.join(", ")}`,
      );
    }
  }

  console.log("Seeding Endlauf events…");
  await seedEvents("hmj");
  await seedEvents("adac_hth");

  console.log("Seeding entries…");
  await seedEntries("hmj");
  await seedAdacEntries(adacSeed.drivers);

  console.log("Storing source documents…");
  await seedDocuments();

  const [{ n }] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(schema.endlauf26Entries);
  console.log(`Done. ${n} entries total.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
