/**
 * Seed the Endläufe 2026 data set from `data/endlauf26/*.json`
 * (generated by `scripts/endlauf26/parse-pdfs.py` from the official PDFs).
 *
 * Idempotent: teams/drivers/season results are upserted on their natural
 * keys; events are upserted by (championship, slug); entries are only
 * inserted when missing so live times are never overwritten.
 *
 * All drivers of the standings lists are imported. Only the qualified ones
 * (plus admins' Nachnominierungen) form the Endlauf field and get entries;
 * the rest stays in the database as the pool of replacement candidates.
 * The admin flags `withdrawn` / `nominated` are never touched by the seed.
 *
 * Run:  cd webapp && npm run db:seed-endlauf26
 *       (or `make seed-endlauf26` from the project root)
 */
import "dotenv/config";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { and, eq, or, sql } from "drizzle-orm";

import * as schema from "../src/db/schema";
import {
  computeEndlauf26Championship,
  type Endlauf26Championship,
  type EndlaufDriverInput,
} from "../src/lib/endlauf26/ranking";

const __filename = fileURLToPath(import.meta.url);

function resolveDataDir(): string {
  const scriptDir = dirname(__filename);
  const candidates = [
    join(dirname(dirname(scriptDir)), "data", "endlauf26"), // repo root
    join(dirname(scriptDir), "data", "endlauf26"), // /app/data in container
  ];
  for (const dir of candidates) {
    if (existsSync(join(dir, "hmj.json"))) return dir;
  }
  throw new Error(`data/endlauf26 not found (tried: ${candidates.join(", ")})`);
}

const DATA_DIR = resolveDataDir();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("ENV ERROR - DATABASE_URL is missing");
const db = drizzle(databaseUrl, { schema });

/* ───────────────────────────── JSON shapes ───────────────────────────── */

interface JsonResult {
  race: number;
  position: number;
  points: number;
  struck: boolean;
}

interface JsonDriver {
  position: number;
  qualified: boolean;
  lastName: string;
  firstName: string;
  club: string;
  racesStarted: number;
  total: number;
  results: JsonResult[];
  verband?: string | null;
  adacId?: string | null;
}

interface JsonClass {
  number: number;
  drivers: JsonDriver[];
}

interface HmjJson {
  championship: "hmj";
  stand: string;
  classes: JsonClass[];
}

interface AdacJson {
  championship: "adac-hth";
  regions: { region: string; stand: string; classes: JsonClass[] }[];
}

/* ───────────────────────────── events ───────────────────────────── */

const EVENTS: Record<
  Endlauf26Championship,
  { number: number; slug: string; name: string; factor: string }[]
> = {
  hmj: [
    { number: 1, slug: "langgoens-1", name: "Langgöns 1", factor: "1.25" },
    { number: 2, slug: "langgoens-2", name: "Langgöns 2", factor: "1.25" },
  ],
  adac_hth: [
    { number: 1, slug: "crumbach", name: "Crumbach", factor: "1.00" },
    { number: 2, slug: "reinheim", name: "Reinheim", factor: "1.00" },
    { number: 3, slug: "malsfeld", name: "Malsfeld", factor: "1.10" },
  ],
};

/* ───────────────────────────── helpers ───────────────────────────── */

async function upsertTeam(
  championship: Endlauf26Championship,
  name: string,
): Promise<number> {
  await db
    .insert(schema.endlauf26Teams)
    .values({ championship, name })
    .onConflictDoNothing();
  const [row] = await db
    .select({ id: schema.endlauf26Teams.id })
    .from(schema.endlauf26Teams)
    .where(
      and(
        eq(schema.endlauf26Teams.championship, championship),
        eq(schema.endlauf26Teams.name, name),
      ),
    )
    .limit(1);
  return row.id;
}

interface DriverSeed {
  championship: Endlauf26Championship;
  ageClass: number;
  driver: JsonDriver;
  region: string | null;
}

async function upsertDriver(
  s: DriverSeed,
  teamIdByName: Map<string, number>,
): Promise<number> {
  let teamId = teamIdByName.get(s.driver.club);
  if (!teamId) {
    teamId = await upsertTeam(s.championship, s.driver.club);
    teamIdByName.set(s.driver.club, teamId);
  }
  const values = {
    championship: s.championship,
    firstName: s.driver.firstName,
    lastName: s.driver.lastName,
    teamId,
    ageClass: s.ageClass,
    verband: s.championship === "hmj" ? (s.driver.verband ?? null) : null,
    region: s.region,
    adacId: s.driver.adacId ?? null,
    seasonPosition: s.driver.position,
    seasonPoints: String(s.driver.total),
    seasonRaces: s.driver.racesStarted,
    qualified: s.driver.qualified,
  };
  const [row] = await db
    .insert(schema.endlauf26Drivers)
    .values(values)
    .onConflictDoUpdate({
      target: [
        schema.endlauf26Drivers.championship,
        schema.endlauf26Drivers.firstName,
        schema.endlauf26Drivers.lastName,
        schema.endlauf26Drivers.teamId,
      ],
      // `withdrawn` / `nominated` are admin decisions — deliberately not reset.
      set: {
        ageClass: values.ageClass,
        verband: values.verband,
        region: values.region,
        adacId: values.adacId,
        seasonPosition: values.seasonPosition,
        seasonPoints: values.seasonPoints,
        seasonRaces: values.seasonRaces,
        qualified: values.qualified,
      },
    })
    .returning({ id: schema.endlauf26Drivers.id });

  for (const r of s.driver.results) {
    await db
      .insert(schema.endlauf26SeasonResults)
      .values({
        driverId: row.id,
        raceNumber: r.race,
        finishPosition: r.position,
        points: r.points,
        struckInSource: r.struck,
      })
      .onConflictDoUpdate({
        target: [
          schema.endlauf26SeasonResults.driverId,
          schema.endlauf26SeasonResults.raceNumber,
        ],
        set: {
          finishPosition: r.position,
          points: r.points,
          struckInSource: r.struck,
        },
      });
  }
  return row.id;
}

async function seedEvents(championship: Endlauf26Championship) {
  for (const e of EVENTS[championship]) {
    await db
      .insert(schema.endlauf26Events)
      .values({ championship, ...e })
      .onConflictDoUpdate({
        target: [schema.endlauf26Events.championship, schema.endlauf26Events.slug],
        set: { number: e.number, name: e.name, factor: e.factor },
      });
  }
}

/**
 * Create the entry list of every event: every driver of the Endlauf field
 * (qualified or nominated), starting order bottom-up (worst pre-Endlauf
 * standing starts first).
 */
async function seedEntries(championship: Endlauf26Championship) {
  const drivers = await db
    .select({
      id: schema.endlauf26Drivers.id,
      firstName: schema.endlauf26Drivers.firstName,
      lastName: schema.endlauf26Drivers.lastName,
      teamId: schema.endlauf26Drivers.teamId,
      ageClass: schema.endlauf26Drivers.ageClass,
      verband: schema.endlauf26Drivers.verband,
      region: schema.endlauf26Drivers.region,
      adacId: schema.endlauf26Drivers.adacId,
      yearOfBirth: schema.endlauf26Drivers.yearOfBirth,
      seasonPosition: schema.endlauf26Drivers.seasonPosition,
      seasonPoints: schema.endlauf26Drivers.seasonPoints,
      seasonRaces: schema.endlauf26Drivers.seasonRaces,
      withdrawn: schema.endlauf26Drivers.withdrawn,
      nominated: schema.endlauf26Drivers.nominated,
    })
    .from(schema.endlauf26Drivers)
    .where(
      and(
        eq(schema.endlauf26Drivers.championship, championship),
        or(
          eq(schema.endlauf26Drivers.qualified, true),
          eq(schema.endlauf26Drivers.nominated, true),
        ),
      ),
    );

  const seasonRows = await db
    .select()
    .from(schema.endlauf26SeasonResults)
    .innerJoin(
      schema.endlauf26Drivers,
      eq(schema.endlauf26Drivers.id, schema.endlauf26SeasonResults.driverId),
    )
    .where(eq(schema.endlauf26Drivers.championship, championship));
  const seasonByDriver = new Map<number, typeof seasonRows>();
  for (const r of seasonRows) {
    const arr = seasonByDriver.get(r.endlauf26_season_results.driverId) ?? [];
    arr.push(r);
    seasonByDriver.set(r.endlauf26_season_results.driverId, arr);
  }

  const inputs: EndlaufDriverInput[] = drivers.map((d) => ({
    driverId: d.id,
    firstName: d.firstName,
    lastName: d.lastName,
    teamId: d.teamId,
    teamName: "",
    ageClass: d.ageClass,
    verband: d.verband,
    region: d.region,
    adacId: d.adacId,
    yearOfBirth: d.yearOfBirth,
    seasonPosition: d.seasonPosition,
    seasonPoints: d.seasonPoints === null ? null : Number(d.seasonPoints),
    seasonRaces: d.seasonRaces,
    withdrawn: d.withdrawn,
    nominated: d.nominated,
    seasonResults: (seasonByDriver.get(d.id) ?? []).map((r) => ({
      raceNumber: r.endlauf26_season_results.raceNumber,
      finishPosition: r.endlauf26_season_results.finishPosition,
      points: r.endlauf26_season_results.points,
    })),
    endlaufResults: [],
  }));

  const events = await db
    .select()
    .from(schema.endlauf26Events)
    .where(eq(schema.endlauf26Events.championship, championship));

  const rows = computeEndlauf26Championship(
    championship,
    inputs,
    events.map((e) => ({
      eventId: e.id,
      number: e.number,
      slug: e.slug,
      name: e.name,
      factor: Number(e.factor),
    })),
  );

  // Bottom-up: last place in the class starts first.
  const startingOrder = new Map<number, number>();
  const byClass = new Map<number, typeof rows>();
  for (const r of rows) {
    byClass.set(r.ageClass, [...(byClass.get(r.ageClass) ?? []), r]);
  }
  for (const list of byClass.values()) {
    const bottomUp = [...list].reverse();
    bottomUp.forEach((r, idx) => startingOrder.set(r.driverId, idx + 1));
  }

  let inserted = 0;
  for (const ev of events) {
    for (const d of drivers) {
      const res = await db
        .insert(schema.endlauf26Entries)
        .values({
          eventId: ev.id,
          driverId: d.id,
          ageClass: d.ageClass,
          startingOrder: startingOrder.get(d.id) ?? null,
        })
        .onConflictDoNothing()
        .returning({ id: schema.endlauf26Entries.id });
      inserted += res.length;
    }
  }
  console.log(`  ${championship}: ${inserted} new entries across ${events.length} events`);
}

/* ───────────────────────────── main ───────────────────────────── */

async function seed() {
  const hmj = JSON.parse(
    readFileSync(join(DATA_DIR, "hmj.json"), "utf-8"),
  ) as HmjJson;
  const adac = JSON.parse(
    readFileSync(join(DATA_DIR, "adac-hth.json"), "utf-8"),
  ) as AdacJson;

  // hmj
  console.log(`Seeding hmj (Stand ${hmj.stand})…`);
  {
    const teamIdByName = new Map<string, number>();
    let qualified = 0;
    let reserve = 0;
    for (const c of hmj.classes) {
      for (const d of c.drivers) {
        await upsertDriver(
          { championship: "hmj", ageClass: c.number, driver: d, region: null },
          teamIdByName,
        );
        if (d.qualified) qualified += 1;
        else reserve += 1;
      }
    }
    console.log(
      `  ${qualified} qualified drivers, ${reserve} replacement candidates, ${teamIdByName.size} clubs`,
    );
  }

  // adac-hth
  console.log("Seeding adac-hth…");
  {
    const teamIdByName = new Map<string, number>();
    let qualified = 0;
    let reserve = 0;
    for (const region of adac.regions) {
      for (const c of region.classes) {
        for (const d of c.drivers) {
          await upsertDriver(
            {
              championship: "adac_hth",
              ageClass: c.number,
              driver: d,
              region: region.region,
            },
            teamIdByName,
          );
          if (d.qualified) qualified += 1;
          else reserve += 1;
        }
      }
      console.log(`  Region ${region.region} (Stand ${region.stand})`);
    }
    console.log(
      `  ${qualified} qualified drivers, ${reserve} replacement candidates, ${teamIdByName.size} clubs`,
    );
  }

  console.log("Seeding Endlauf events…");
  await seedEvents("hmj");
  await seedEvents("adac_hth");

  console.log("Seeding entries (starting order bottom-up)…");
  await seedEntries("hmj");
  await seedEntries("adac_hth");

  const [{ n }] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(schema.endlauf26Entries);
  console.log(`Done. ${n} entries total.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
